FROM arm32v7/busybox:1.27.2

EXPOSE 9090

COPY scripts/start.sh /app/
COPY dist/github.com/blinkinglight/mikrotik-exporter_linux_arm /app/github.com/blinkinglight/mikrotik-exporter

RUN chmod 755 /app/*

ENTRYPOINT ["/app/start.sh"]